name: amass_engine
description: Attack surface mapping and external asset discovery engine for Dart & Flutter. Inspired by OWASP Amass.
version: 2.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
